### PR TITLE
Transform urls for better tts experience

### LINKED ISSUE #15: Don't read urls
Before doing tts urls should be replaced with something similar.

e.g
```
"https://www.youtube.com/watch?v=QH2-TGUlwu4" -> "a link to youtube.com"
```

### PR DESCRIPTION
**Pull request by FabioRosado**
This is my attempt on issue 15, all the tests I have done seem to change the text to the desired format.

Let me know what you do you about this and if I should change something.

Fixes #15

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Good stuff!

As you can see I haven't looked at this project for about nine months. Have you done local testing? Does it still work?

**Comment by jacobtomlinson** [comment]
Also instead of calling your method in both generators you could just do it once in the [main generate text method](https://github.com/opsdroid/opsdroid-audio/blob/master/opsdroidaudio/__main__.py#L222).

**Comment by FabioRosado** [comment]
I haven't actually tested it with voice, I'll give it a go and see how this bit of code behaves 👍 
Also thanks for the suggestion I was unsure where to put it, i'll change it so it's only called in  the generate_speech

**Comment by jacobtomlinson** [comment]
How did your testing go?

**Comment by FabioRosado** [comment]
I have some time today to test it, been busy most of the weekend/week. Im currently having issues with snowboy, I've ran the script but when I run opsdroid audio it says that it couldnt find snowboy, ill try to figure something out

**Comment by jacobtomlinson** [comment]
No worries! This will be a good test for the documentation. Have you [installed snowboy](https://github.com/opsdroid/opsdroid-audio#installation)?

**Comment by FabioRosado** [comment]
Yeah but it didn’t work it seems I’m giving another try in a comment

**Comment by FabioRosado** [comment]
So i've tried to install snowboy again without success.
 When I try to run the command: `python3 -m opsdroidaudio`

This is the traceback error that i get
```
Traceback (most recent call last):
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/snowboydetect/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit__snowboydetect)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/opsdroidaudio/__main__.py", line 18, in <module>
    import opsdroidaudio.audio as audio
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/opsdroidaudio/audio.py", line 11, in <module>
    from snowboydetect import snowboydetect
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/snowboydetect/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/snowboydetect/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_snowboydetect'
```

I was reading about it but Im not sure how to fix this issue at the moment

**Comment by jacobtomlinson** [comment]
If I remember correctly the command `scripts/install_snowboy.sh -i ./` should create the `_snowboydetect` module in your current directory. Does this happen for you?

**Comment by FabioRosado** [comment]
yeah the directory was created but the error persists. Also, if I try to run opsdroidaudio with the command: `python3 opsdroidaudio` I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "opsdroidaudio/__main__.py", line 18, in <module>
    import opsdroidaudio.audio as audio
ModuleNotFoundError: No module named 'opsdroidaudio'
```

I tried to change the imports but that didnt seem to work. Have you had any success running opsdroid audio lately?

**Comment by jacobtomlinson** [comment]
I just managed to get it running. It looks like snowboy is being built for python 2 and then you are trying to use it with python 3.

Here are some updated install instructions:

```
# Clean up Python 2 version
rm -rf snowboydetect

# Install system libraries
brew install swig portaudio pocketsphinx

# Close opsdroid audio
git clone https://github.com/opsdroid/opsdroid-audio.git /path/to/opsdroid-audio
cd /path/to/opsdroid-audio

# Create and activate virtual environment
virtualenv venv -p python3
source venv/bin/activate

# Compile snowboy module
scripts/install_snowboy.sh -i ./

# Install python deps
pip install -r requirements.txt

# run opsdroid audio
python -m opsdroidaudio
```

**Comment by FabioRosado** [comment]
I am still having issues with snowboydetect. I've removed opsdroid-audio fully and followed those steps. I've also noticed that snowboydetect installed its version fit for python3.

When I try to run opsdroid-audio this is what I get:
```
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/opsdroidaudio/__main__.py", line 250, in <module>
    main()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/opsdroidaudio/__main__.py", line 246, in main
    oaudio.start()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/opsdroidaudio/__main__.py", line 52, in start
    self.detector = audio.HotwordDetector(self.model, sensitivity=0.4)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/opsdroidaudio/audio.py", line 117, in __init__
    model_str=str(model_str.encode()))
  File "/Users/fabiorosado/Documents/GitHub/opsdroid-audio/snowboydetect/snowboydetect.py", line 106, in __init__
    this = _snowboydetect.new_SnowboyDetect(resource_filename, model_str)
TypeError: in method 'new_SnowboyDetect', argument 1 of type 'std::string const &'
```
I did a quick search and it seems the problem is that snowboydetect installed the python2 version, which is odd since I have started from a clean install and ran the python3 command

**Comment by jacobtomlinson** [comment]
This command `scripts/install_snowboy.sh -i ./` checks what version of python you get then you run `python`. Which is why it is building for Python 2. Hence why I suggested using a virtual environment.

**Comment by FabioRosado** [comment]
I did use the virtual env and snowboy installed the python3 version. That's why I don't get it why the error is being thrown

**Comment by jacobtomlinson** [comment]
What happens if you run `python --version` within your virtual env?

**Comment by FabioRosado** [comment]
Sorry for the delayed reply, when I check the version of python with that command it shows that the version `3.6.1` is being used

**Comment by jacobtomlinson** [comment]
Hmm that is odd. Well I'm going to merge this because I'm happy with it and that opsdroid-audio still works. But I would appreciate if you could keep trying to get it to run on your machine.

**Pull request closed without merging**
